### ISSUE TITLE
Clicking cancel will throw an exception

### ISSUE THREAD

**Issue by a-catgirl-dev** [tristanpoland/Number-guess#1]
//below: basically..
//catch the frisbee i call exception!
//above: basically, i stol minenecraf!

ACTUAL USEFUL EDIT:
entering nothing also causes the same, "as it returns null" -tristan
![image](https://user-images.githubusercontent.com/75321465/156479795-1f64e171-18be-4fa2-b4bf-b02e553b3089.png)
(note: tristan made that idea, not me)

Steps to reproduce: start the game, then click cancel, or type random letters (eg ffffff), or empty
![image](https://user-images.githubusercontent.com/75321465/156479170-074909b5-4193-4251-9cef-c9e038b89a98.png)

**Comment by a-catgirl-dev** [comment]
fixed in [1.20 RC1](https://github.com/tristanpoland/Number-guess/releases/tag/v1.2.0)

**Comment by tristanpoland** [comment]
Appreciate the assistance @WilliamAnimate!
